### ISSUE TITLE
GUI無故中斷運行

### ISSUE THREAD

**Issue by ericjing1** [FeixiDev/VersaTEL_G1_Code#18]
啟用GUI後數日，GUI發生中斷運行狀況；於代碼執行視窗按下回車鍵則可以使GUI重新運行.

已反饋此一異常狀況給Paul知悉.

**Comment by Paulbig** [comment]
![屏幕快照 2020-05-11 下午1 24 05](https://user-images.githubusercontent.com/42997375/81776982-7c983d00-9522-11ea-8520-db192ea6fc67.png)
由于Sundry模块的缩略名s，和s = second uptime中变量名s，出现命名冲突，导致代码执行到这里的时候，出现变量 s 在使用前被定义的错误，所以程序在这里卡住了。解决方法:修改变量名s为st，命名不冲突，程序继续运行测试。等待下次意外情况（发送预警邮件）出现

**Comment by userhei** [comment]
这个不是也解决了吗？
