### ISSUE TITLE
python pyinstaller打包报错No trigger by the name "cron" was found

### ISSUE THREAD

**Issue by Paulbig** [FeixiDev/VersaTEL_G1_Code#20]
![屏幕快照 2020-05-12 下午5 23 43](https://user-images.githubusercontent.com/42997375/81778846-23320d00-9526-11ea-9c1d-d910b9d5d5b7.png)
原因:
感觉好像是由于pyinstaller打包的时候使用了错误版本的APScheduler。（不确定）？？？

解决方法:
不要在add_job方法中使用“’cron’, seconds=2”做trigger，而是先创建一个CronTrigger对象，然后add_job的时候使用这个对象

修改后代码:
```
from apscheduler.triggers.cron import CronTrigger

if cycle_meg == 'week':
            trigger = CronTrigger(day=day_meg, hour=hour_meg, minute=minutes_meg)
            self.scdl.add_job(job, trigger)
elif cycle_meg == 'day':
            trigger = CronTrigger(hour=hour_meg, minute=minutes_meg)
            self.scdl.add_job(job, trigger)

```

**Comment by mattie-feng** [comment]
尽量使用模板进行信息填写

**Comment by userhei** [comment]
不小心关闭了，现在pyinstaller应该是已经可以打包了吧
