### ISSUE TITLE
输出软件版本

### ISSUE THREAD

**Issue by klaylin** [FeixiDev/VersaTEL_G1_Code#21]
**Is your feature request related to a problem? Please describe.**
不知道当前软件版本，有时使用过程中不确定软件是否是当前最新的
**Describe the solution you'd like**
可以有命令输出当前版本
例如可以输入命令“VersaTEL -v ”，输出“VersaTEL 1.0.0”

**Comment by mattie-feng** [comment]
之后会增加输出版本信息的功能
