### ISSUE TITLE
pc & gt 功能不稳定

### ISSUE THREAD

**Issue by klaylin** [FeixiDev/VersaTEL_G1_Code#22]
**Describe the bug**
执行gt或pc命令，没有输出也没有报错，没有生成pc或trace文件，有重复发生。
引擎状态正常，可以手动抓取trace。

**To Reproduce**
1. 如以下截图

**Screenshots**
![8221589779901_ pic](https://user-images.githubusercontent.com/42958736/82177793-2bff5600-990d-11ea-8870-b9cc8c3796f0.jpg)
![8211589779845_ pic](https://user-images.githubusercontent.com/42958736/82177818-37eb1800-990d-11ea-8325-730eadbbff58.jpg)

**Comment by klaylin** [comment]
经过测试，这两个功能的不正常现象应该与引擎user menu的命令字符串有关：
如果是“HA-AP”，则运行正常
![haap](https://user-images.githubusercontent.com/42958736/82180790-d7aba480-9913-11ea-81bd-d2925e292154.png)


如果是“CIO”，则会出现此问题，并且其他命令也会受到影响
![cio](https://user-images.githubusercontent.com/42958736/82180810-df6b4900-9913-11ea-8cd6-446300f22ec2.png)

**Comment by mattie-feng** [comment]
"CIO"和"HA-AP"通过什么操作可以相互转换呢？

**Comment by klaylin** [comment]
"CIO"和“HA-AP”对应不同版本FW

**Comment by klaylin** [comment]
“CIO”应该对应的是帮银兴改的FW code，所以其他版本的FW可能都是“HA-AP”。不过我不能完全确定。

**Comment by mattie-feng** [comment]
"CIO"修改成"HA-AP"是在FW中的代码中修改的吗？

**Comment by klaylin** [comment]
嗯，是的

**Comment by mattie-feng** [comment]
可在配置文件Config.ini的[General]配置中对应修改PRODUCT值为HA-AP或者CIO
```
[General]
company = SILVERstor
#PRODUCT = ClusterIO
PRODUCT = HA-AP
location = Taiwan
```

**Comment by klaylin** [comment]
OK
