### ISSUE TITLE
缺少Python模块

### ISSUE THREAD

**Issue by mattie-feng** [FeixiDev/VersaTEL_G1_Code#3]
**Describe the bug**
使用VersaTEL分析Trace时出现错误，提示缺少xlwt包

**Expected behavior**
程序能正常分析Trace

**Screenshots**
![image_2020_04_24T01_51_22_029Z](https://user-images.githubusercontent.com/61734479/80226727-513ad480-867f-11ea-8113-fee2a9d30e91.png)

**Comment by mattie-feng** [comment]
使用requirements文件（记录所有依赖包及其精确的版本号）能否解决导入模块缺失的问题

[Python项目之requirements文件](https://www.cnblogs.com/edwardX/p/11548800.html)

**Comment by userhei** [comment]
是这样吗？

**Comment by mattie-feng** [comment]
因为经常会出现打包成可执行文件时没有导入某一些模块的错误，就是看使用requirements文件能不能解决这个问题。

**Comment by userhei** [comment]
这个能记录的，pyinstall 打包时候也就会打进去，难道你没有发现根本的原因吗？？？

**Comment by mattie-feng** [comment]
不清楚

**Comment by Paulbig** [comment]
测试代码的环境没弄好，没在打包的环境中完整测试过代码
----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Mark "<notifications@github.com&gt;;
发送时间：2020年6月2日(星期二) 上午10:43
收件人："FeixiDev/VersaTEL_G1_Code" <VersaTEL_G1_Code@noreply.github.com&gt;;
抄送："Paulbig "<paul.wen@feixitek.com&gt;;"Assign "<assign@noreply.github.com&gt;;
主题：Re: [FeixiDev/VersaTEL_G1_Code] 缺少Python模块 (#3)
-----------------------------------

 

 
这个能记录的，pyinstall 打包时候也就会打进去，难道你没有发现根本的原因吗？？？
