### ISSUE TITLE
安全漏洞提醒

### ISSUE THREAD

**Issue by code6er** [FeixiDev/VersaTEL_G1_Code#34]
漏洞类型：邮箱 SMTP 信息泄露

漏洞等级：高

漏洞地址：https://github.com/FeixiDev/VersaTEL_G1_Code/blob/faa4357b29ee15f95b7c03a0a9c08a9919e7fc0a/Config.ini

漏洞危害：任何人可以通过 SMTP 账号密码收发邮件，进而通过邮箱重置其他平台密码

解决方案：重置 SMTP 密码并修改代码

本次扫描结果由 [ 码小六 ] https://github.com/4x99/code6 提供（欢迎 star）

**Comment by userhei** [comment]
刚想说不要把config文件提交上来，结果就有好心人来提醒了。。

**Comment by mattie-feng** [comment]
还是说把Config文件里的一些账户信息的配置就写成“value=xxx"，如password = xxx这样就好了，自己需要使用时再进行修改。

**Comment by userhei** [comment]
可以
