### ISSUE TITLE
邮件模块，邮件账号/密码带特殊符号无法登录

### ISSUE THREAD

**Issue by Zaneczy** [FeixiDev/VersaTEL_G1_Code#37]
**Describe the bug**
邮件模块，邮件账号/密码带特殊符号无法登录，特殊符号如 ; / \ 等。

**To Reproduce**
步骤:
1. 修改配置文件中password（带特殊字符）
2. 运行网页
3. 点击右上角测试邮件发送

**结果**
发送失败，显示邮件登录失败

**Expected behavior**
账号/密码带特殊符号可以正常运行

**Screenshots**
![屏幕快照 2020-06-02 下午4 27 04](https://user-images.githubusercontent.com/46948213/83498252-39f8cd80-a4ee-11ea-982d-c96ae6d550d0.png)

**Comment by mattie-feng** [comment]
在自建服务器测试带特殊符号可以登录
