### ISSUE TITLE
代码冗余，有部分函数未被调用

### ISSUE THREAD

**Issue by Zaneczy** [FeixiDev/VersaTEL_G1_Code#54]
**问题描述**
1. SANSW.py 模块中Status类，其中有4个函数未被调用到。
a. sum_total_and_warning()
b. get_linkfail_by_port()
c. get_encout_by_port()
d. get_discC3_by_port()
2. SANSW.py 模块中Action类，clear_one_port()跟clear_all_port()两个功能相同的函数，清除单个端口错误计数函数 跟 清除所有已配置交换机端口错误计数函数，一个有return True 另一个没有。

**建议**
1. 后续会开发相关用处的话要标记备注下，多余的并且后续也不会用到的要删除。
2. 建议统一加入return True（测试代码运行起来会比较快），或者统一删除（代码看起来比较整洁）。

**Comment by mattie-feng** [comment]
保留及添加注释：
* get_linkfail_by_port()
* get_encout_by_port()
* get_discC3_by_port()

删除：
* sum_total_and_warning()
