### ISSUE TITLE
引擎在断网的情况下，会出现误报警状况

### ISSUE THREAD

**Issue by mattie-feng** [FeixiDev/VersaTEL_G1_Code#9]
**Describe the bug**
正常情况下，引擎断网时获取到的realtime为空值，且不会发送报警邮件。
但是在引擎断网时，有几率会获取到为0的realtime值，导致程序发送引擎在0秒前发生reboot的邮件，出现误报警情况。

**Expected behavior**
断网的情况下不会发送报警邮件。

**Additional context**
realtime为0是通过查看数据库得到的数据

**Comment by Feixitek** [comment]
代码修改：
https://github.com/FeixiDev/VersaTEL_G1_Code/blob/4cc536fc0eda0420f431e40147e908027b1d88b1/Monitor.py#L281-L292
测试中...

**Comment by userhei** [comment]
测试结果如何，到现在为止，正常吗

**Comment by mattie-feng** [comment]
From Paul：
台湾环境中已经测试了三天，暂时未出现问题

**Comment by userhei** [comment]
这个Comment Paul的邮箱收不到吗？你让他登录注册邮箱看一下。

**Comment by mattie-feng** [comment]
刚才他邮箱有点问题，现在解决好了

**Comment by userhei** [comment]
好，你后续跟进每一个Issue的处理情况，及时更新状态，需要和我确认的及时和我确认。

**Comment by userhei** [comment]
那么@Paul，这个问题是因为引擎断网吗？

**Comment by Paulbig** [comment]
进入引擎后执行vpd命令失败了

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Mark "<notifications@github.com&gt;;
发送时间：2020年5月26日(星期二) 下午4:43
收件人："FeixiDev/VersaTEL_G1_Code" <VersaTEL_G1_Code@noreply.github.com&gt;;
抄送："Paulbig "<paul.wen@feixitek.com&gt;;"Assign "<assign@noreply.github.com&gt;;
主题：Re: [FeixiDev/VersaTEL_G1_Code] 引擎在断网的情况下，会出现误报警状况 (#9)
-----------------------------------

 

 
那么@paul，这个问题是因为引擎断网吗？
